- delivery/CNABwithPorter/.dockerignore
- delivery/CNABwithPorter/.gitignore
- delivery/CNABwithPorter/Dockerfile.tmpl
- delivery/CNABwithPorter/README.md
- delivery/CNABwithPorter/helpers.sh
- delivery/CNABwithPorter/manifests/manifest.yaml
- delivery/CNABwithPorter/porter.yaml
- docs/cnabWithPorter.md
This updates the airgap example to demonstrate how to include referenced images in the bundle when it is archived to a tgz, and how to update your manifests to use the new image location after the images are published on the other side of the airgap.
With helm's set command this is a bit easier to accomplish, here is an example bundle that uses helm:
https://github.com/getporter/porter/tree/main/examples/airgap
I am using yq to help modify the manifest. I think kustomize can do it as well.
> Update CNAB airgap example

- delivery/CNABwithPorter/manifests/manifest.yaml
- delivery/hello-operator/helm-charts/helloserver/templates/service.yaml
- delivery/keptn/helm-charts/helloserver/templates/service.yaml
The `type` key was duplicated in some of the YAML files and has now been deleted.
> Removed duplicated keys in YAML files

- README.md
- delivery/CNABwithPorter/manifests/manifest.yaml
- delivery/KubeVela/vela.yaml
- delivery/charts/hello-server/values.yaml
- delivery/keptn/helm-charts/helloserver/values.yaml
- hello-server/buildPush.sh
This PR fixes #15  to changes all container image references to ghcr.io/podtato-head
> changed manifests and other files to use ghcr.io as container registry.

- hello-server/helloserver.go
Changing the Prometheus endpoint to `/metrics` according to the Prometheus documentation. The endpoint `/metrics` is also defaulted by the [Keptn Prometheus Services](https://github.com/keptn-contrib/prometheus-service/blob/master/deploy/service.yaml#L212). 
#26
> Changed Prometheus endpoint to /metrics

- delivery/keptn/shipyard.yaml
Now that [Keptn v0.8.0](https://github.com/keptn/keptn/releases/tag/0.8.0) is released the shipyard needs to be updated to be compatible with the new Keptn version. More information about the new Keptn shipyard file can be found [here](https://keptn.sh/docs/0.8.x/continuous_delivery/multi_stage/#declare-shipyard-before-creating-a-project).
> Update Keptn shipyard for v0.8.0

- delivery/keptn/shipyard.yaml
Shipyard syntax was updated from `v0.8.0-alpha` to `v0.8.0`.
> Update shipyard for new v0.8.0

- .github/workflows/buildcontainers.yml
There is a typo in the `buildcontainers` action which prevents the action from completing successfully.
> Fixed typo in buildcontainers action

- podtato-server/buildPush.sh
The container image names in the `buildPush.sh` file do not match and the [Github action](https://github.com/cncf/podtato-head/runs/2140717646?check_suite_focus=true#step:4:124) fails because of that. I omitted the `-` since other files already use the `podtatoserver` image name ([Example](https://github.com/cncf/podtato-head/blob/main/delivery/charts/podtatoserver/values.yaml#L8)).
> Fixed image name in buildPush

- podtato-server/DockerfileV0.1.0
- podtato-server/DockerfileV0.1.1
- podtato-server/DockerfileV0.1.2
The `podtatoserver.go` file refers to the [podtato-new.html](https://github.com/cncf/podtato-head/blob/main/podtato-server/podtatoserver.go#L84) file, but the Dockerfile copies `overview.html` which results in an error when accessing the site.
> Fix HTML file path in Dockerfile

- delivery/keptn/helm-charts/helloserver/templates/service.yaml
- change `type` to `ClusterIP` to save loadbalancer resources (and service will be exposed via Istio Ingress anyway
- change service port to standard port 80 for Prometheus to query the metrics
> change type and port in Helm chart

- delivery/keptn/slo.yaml
The Keptn Quality gates failed on some occasions because the number of Goroutines was set to low in the SLO file.
> Changed goroutines limit in slo file

- delivery/keptn/jmeter/jmeter.conf.yaml
The performance testing strategy took a long time when testing the slow build version (10 minutes +), which is too long for an example application.
> Jmeter testing config

- .github/workflows/buildcontainers.yml
I noticed github actions are failing after the merged PR with the folder directory changes.
This fixes that issue.
> fix(build): failing build script path

- podtato-server/kind/README.md
- podtato-server/kind/cluster.yaml
- podtato-server/kind/full_install.sh
- podtato-server/kind/traefik_dashboard.yaml
- podtato-server/kind/traefik_values.yaml
This provides a KIND configuration to test the examples on your local machine. KIND is configured with NodePort and Ingress support using Traefik
> add KIND configuration

- delivery/manifest/manifest.yaml
Adding a label to the kubernetes service of the podtato head app helps with setting up (prometheus) servicemonitors against it. 
Signed-off-by: ksatchit <karthik@chaosnative.com>
> (chore)helloservice: add label to the kubernetes service for podtato-head app

- delivery/keptn/README.md
- delivery/keptn/initProject.sh
Fixes `Error: Provided Helm chart does not exist` when executing `./initProject.sh onboard-service`.
> fix(keptn): fixed wrong path to helm-chart and updated initProject.sh to work with keptn 0.8.6

- .github/workflows/build.yaml
- README.md
- contributing.md
- delivery/chart/test.sh
- delivery/kubectl/test.sh
- adds a workflow job `build_container` which builds and pushes images to a repo accessible to the owner of the current fork
- renames the main container build job `build_container_main`
- updates `contributing.md` to reflect these changes
- uses `github.token` for the registry login rather than `secrets.CR_PAT`; the former is available in forks too, the latter isn't
- extracts tests for `kubectl` and `helm` into their directories and runs them from there in the workflow
Without this, tests in forks can't use freshly built Go binaries and images because they don't have a registry to push to and pull from. As a result developers can't verify new functionality.
This also provides a framework for tests in each delivery directory.
Successful test run: …
> make GH action work in forks

- .github/workflows/build.yaml
- delivery/chart/test.sh
- delivery/kubectl/test.sh
- Revert to custom secret for main container build since it pushes to `ghcr.io/podtato-head` and not `ghcr.io/cncf/podtato-head`.
- Add image pull secret for ghcr.io to kind cluster before delivering app.
Fixes #94
> use custom secret for main container build, add pull secret to test cluster

- .github/workflows/build.yaml
- .github/workflows/fork-test.yaml
- delivery/chart/test.sh
- delivery/kubectl/test.sh
This reverts the main build workflow to the known-working state it was in in <https://github.com/cncf/podtato-head/commit/490a8ebc54e4b63c33babf383b5beadc3032d85e> plus additions from <https://github.com/cncf/podtato-head/commit/1a1647b6144e7259c2dfe06ed2b0981cb13e4781>.
It adds a _separate_ test for forks, which succeeded in my fork: <https://github.com/joshgav/podtato-head/actions/runs/1222555931>.
I believe this will finally fix #94. Thanks!
> revert main workflow, add fork workflow

- build/main.sh
Fix to correct:
* The build.sh script fails due to an incorrect path for the "podtato-services/main/docker/Dockerfile"
* The build.sh script results in tags like "vv1" rather than utilizing the declared tag values
> fixing build/main.sh path to main image as well as tagging

- delivery/kapp/README.md
kubectl, helm and kustomize have been refactored. Kapp is using these tools so this PR aims to align the path for kapp examples to work successfully again.
> Fix kapp intructions to align to other tools refactoring

- delivery/kustomize/base/service-left-arm.yaml
The left arm image was missing in the final image after a deployment from kustomize base : the reason was an error on the service port.
> Fix left-arm kustomize service

- delivery/chart/Chart.yaml
- delivery/chart/README.md
- delivery/chart/templates/deployment-entry.yaml
- delivery/chart/templates/deployment-hat.yaml
- delivery/chart/templates/deployment-left-arm.yaml
- delivery/chart/templates/deployment-left-leg.yaml
- delivery/chart/templates/deployment-right-arm.yaml
- delivery/chart/templates/deployment-right-leg.yaml
- delivery/chart/test.sh
- delivery/chart/values.yaml
PR purpose:
In order to change the podtato part via environment variable, the helm chart has been updated to reflect 
Fixes:
https://github.com/podtato-head/podtato-head/issues/140
Other info:
Updated readme and bumped up the helm chart version in the Chart.yaml from 0.1.0 to 0.1.1
> adding ability to set deployment extra env variables for things like specifying the part number

- README.md
podtato-head man disappeared after #142! This fixes that and a couple other paths in the README.
> fix README links following microservices/server split

- delivery/kustomize/README.md
- delivery/kustomize/base/deployment-entry.yaml
- delivery/kustomize/base/deployment-hat.yaml
- delivery/kustomize/base/deployment-left-arm.yaml
- delivery/kustomize/base/deployment-left-leg.yaml
- delivery/kustomize/base/deployment-right-arm.yaml
- delivery/kustomize/base/deployment-right-leg.yaml
- delivery/kustomize/overlay/kustomization.yaml
PR purpose:
In order to change the podtato part via environment variable, the kustomize delivery method has been updated to reflect
Fixes:
https://github.com/podtato-head/podtato-head/issues/140
Other info:
Updated kustomize base resources with a single env value (same as was done with the helm chart), set basic tcp probes on all parts (except entry, it already has working http probes), added an example in the overlay/kustomization.yaml on how to set part number on all deployments or a specific deployment, and updated kustomize readme
> updating deploy kustomization section to allow for env to be set to change parts, also enabled basic tcp probes for services without one defined

- README.md
- podtato-head-server/build/test_image.sh
- adds the WAIT_FOR_DELETE env var to the [single-server test-image script](./podtato-head-server/build/test_image.sh)
- adds a note about the env var to the README (it's already in the multi-service test.sh scripts)
- clarified in the README that both multi-service and single-server apps will coexist
> add WAIT_FOR_DELETE to single-server
